// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMmxIbT8rj2SKzafDFSg-1I7c3JWITs-s',
    appId: '1:114204558276:web:29164975c607dd90945a91',
    messagingSenderId: '114204558276',
    projectId: 'calendarapp-31739',
    authDomain: 'calendarapp-31739.firebaseapp.com',
    storageBucket: 'calendarapp-31739.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz06s34rDBE2VziNlMRTvEG-NOE5wrb9g',
    appId: '1:114204558276:android:54cb119d7d797a2f945a91',
    messagingSenderId: '114204558276',
    projectId: 'calendarapp-31739',
    storageBucket: 'calendarapp-31739.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSo_mLaJ-oDgiNt7kRHGr1cXCIIqNtzzw',
    appId: '1:114204558276:ios:6de7b2b35415bf22945a91',
    messagingSenderId: '114204558276',
    projectId: 'calendarapp-31739',
    storageBucket: 'calendarapp-31739.appspot.com',
    iosBundleId: 'com.example.calendarApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSo_mLaJ-oDgiNt7kRHGr1cXCIIqNtzzw',
    appId: '1:114204558276:ios:6de7b2b35415bf22945a91',
    messagingSenderId: '114204558276',
    projectId: 'calendarapp-31739',
    storageBucket: 'calendarapp-31739.appspot.com',
    iosBundleId: 'com.example.calendarApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMmxIbT8rj2SKzafDFSg-1I7c3JWITs-s',
    appId: '1:114204558276:web:b1ed6a5585d3d165945a91',
    messagingSenderId: '114204558276',
    projectId: 'calendarapp-31739',
    authDomain: 'calendarapp-31739.firebaseapp.com',
    storageBucket: 'calendarapp-31739.appspot.com',
  );
}
